cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart

urlpatterns = [
    url(r'^$', view_cart, name='view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name='add_to_cart'),
    url(r'^adjust/(?P<id>\d+)', adjust_cart, name='adjust_cart'),
]

issue_tracker_0_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.urls import path
from django.views import static
from accounts import urls as accounts_urls
from products import urls as products_urls
from home import urls as home_urls
from cart import urls as carts_urls
from checkout import urls as checkout_urls
from comments import urls as comments_urls
from .settings import MEDIA_ROOT


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(home_urls)),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^products/', include(products_urls)),
    url(r'^cart/', include(carts_urls)),
    url(r'^checkout/', include(checkout_urls)),
    url(r'^comments/', include(comments_urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
]

products/urls.py
from django.conf.urls import url
from .views import all_products, new_product, edit_product, delete_product
from .views import all_product_areas, new_product_area
from .views import edit_product_area, delete_product_area

urlpatterns = [
    url(r'^$', all_products, name='products'),
    url(r'^new$', new_product, name='new_product'),
    url(r'^edit/(?P<id>\d+)/$', edit_product, name='edit_product'),
    url(r'^(?P<id>\d+)/delete$', delete_product, name='delete_product'),
    url(r'^areas$', all_product_areas, name='product_areas'),
    url(r'^area/new$', new_product_area, name='new_product_area'),
    url(r'^area/edit/(?P<id>\d+)/$',
        edit_product_area, name='edit_product_area'),
    url(r'^area/(?P<id>\d+)/delete$',
        delete_product_area, name='delete_product_area'),
]
# TODO: avoid page not found errors, redirect to home

products/models.py
import os
import re
from django.db import models
from django.forms import ModelForm
from django.db.models import Count, Sum
from django.core.validators import FileExtensionValidator, RegexValidator
from datetimeutc.fields import DateTimeUTCField


class ProductArea(models.Model):
    name = models.CharField(max_length=254, blank=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    THREE_CHOICES = (
        ('L', 'Low'),
        ('M', 'Medium'),
        ('H', 'High'),
    )

    STATUS = (
        ('T', 'To Do'),
        ('D', 'Doing'),
        ('C', 'Complete'),
    )

    PRODUCT_TYPE = (
        ('I', 'Issue'),
        ('F', 'Feature'),
    )

    user_id = models.IntegerField()
    name = models.CharField(max_length=254, blank=False, validators=[RegexValidator(regex=r'[\w\s\d]+', message='Name can only have letters, Numbers and Spaces', ), ])
    description = models.TextField(blank=False)
    # this is the amount to be paid for the feature/issue
    # to be added to the total_amount_paid
    price = models.DecimalField(max_digits=6, decimal_places=2)
    # this is the cumulative amount paid by users to fix the issue
    total_amount_paid = models.DecimalField(
        max_digits=6, decimal_places=2, default=0.00)
    # product area
    product_area = models.ForeignKey(ProductArea, on_delete=models.CASCADE)
    # product_need is urgency
    product_need = models.CharField(max_length=1, choices=THREE_CHOICES)
    # product_complexity is urgency
    product_complexity = models.CharField(max_length=1, choices=THREE_CHOICES)
    # status of the freature or issue
    status = models.CharField(max_length=1, choices=STATUS)
    # product type bug/issue or feature
    product_type = models.CharField(max_length=1, choices=PRODUCT_TYPE)
    # image of product and/or proposed functional enhancement
    image = models.ImageField(upload_to='images', blank=True)
    # technical documenation related to the product
    # and/or proposed functional enhancement
    product_document = models.FileField(
        upload_to='product_documents',
        blank=True,
        validators=[FileExtensionValidator(
            allowed_extensions=['pdf', 'doc', 'docx', 'txt'])])

    @property
    def filename(self):
        return os.path.basename(self.product_document.name)

    @property
    def total_votes(self):
        return self.productvote_set.count()

    @property
    def total_time(self):
        default = 0
        return self.producttimeassigned_set.aggregate(total=Sum("time_minutes"))["total"] or default

    def save(self, *args, **kwargs):
        # object already exists in db
        if self.pk:
            old_model = Product.objects.get(pk=self.pk)

            if self.image is None:
                self.image = old_model.image

            if self.product_document is None:
                self.product_document = old_model.product_document

        # call the inherited save method
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductVote(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user_id = models.IntegerField()
    submitted = DateTimeUTCField(auto_now_add=True)

    def __str__(self):
        return self.product


class ProductTimeAssigned(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    submitted = DateTimeUTCField(auto_now_add=True)
    time_minutes = models.IntegerField(default=0)

    @property
    def total_time(self):
        return self.productvote_set.count()

    def __str__(self):
        return self.product

products/forms.py
from django import forms
from django.conf import settings
from .models import Product, ProductArea
from django.template.defaultfilters import filesizeformat


class NewProductForm(forms.ModelForm):
    '''
    Form used to create a new product (feature/issue)
    '''

    class Meta:
        model = Product
        fields = [
            'name', 'description', 'price', 'product_area',
            'product_need', 'product_complexity', 'status', 'product_type',
            'image', 'product_document']

    def __init__(self, *args, **kwargs):
        self.id = kwargs.pop('id', None)
        super(NewProductForm, self).__init__(*args, **kwargs)

    def clean(self):
        super(NewProductForm, self).clean()
        if 'product_area' in self._errors:
            del self._errors['product_area']
        return self.cleaned_data

    def clean_name(self, **kwargs):
        name = self.cleaned_data.get('name')
        pk = self.instance.id

        if pk is None:
            if Product.objects.filter(name__iexact=name):
                raise forms.ValidationError(u'Name must be unique')
        elif pk:
            if Product.objects.filter(name__iexact=name).filter(id=pk):
                return name
            else:
                if Product.objects.filter(name__iexact=name):
                    raise forms.ValidationError(u'Name must be unique')
        return name

    def clean_image(self):

        image = self.cleaned_data['image']
        if image is None:
            return 'images/image_placeholder.jpeg'
        else:
            return image

    def clean_product_document(self):
        '''
        Function taken from https://stackoverflow.com/questions/4853581/django-get-uploaded-file-type-mimetype
        '''

        file = self.cleaned_data['product_document']
        if file is None or isinstance(file, str):
            return file
        else:
            try:
                if file:
                    file_type = file.content_type.split('/')[0]

                    if len(file.name.split('.')) == 1:
                        raise forms.ValidationError(u'File type is not supported')

                    if file_type in settings.TASK_UPLOAD_FILE_TYPES:
                        if file.size > int(settings.TASK_UPLOAD_FILE_MAX_SIZE):
                            raise forms.ValidationError(('Please keep filesize under %s. Current filesize %s') % (filesizeformat(settings.TASK_UPLOAD_FILE_MAX_SIZE), filesizeformat(file.size)))
                    else:
                        raise forms.ValidationError(('File type is not supported'))
            except AttributeError:
                pass

        return file


class NewProductAreaForm(forms.ModelForm):
    """Form used to create a new product area."""

    class Meta:
        model = ProductArea
        fields = ['name']

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if ProductArea.objects.filter(name__iexact=name):
            raise forms.ValidationError(u'Name must be unique')
        return name

products/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from checkout.models import Sale, SaleProduct
from .models import Product, ProductVote, ProductArea, ProductTimeAssigned
from .forms import NewProductForm, NewProductAreaForm


@csrf_protect
def all_products(request):
    if request.is_ajax() and request.method == 'POST':
        current_user = request.user

        if request.POST['action_type'] == 'vote':
            # first check that user has not voted previously
            if ProductVote.objects.filter(
                user_id=current_user.id).filter(
                    product=request.POST['vote_id']):
                return HttpResponse(0)

            try:
                product = Product.objects.filter(id=request.POST['vote_id'])
                # if its an issue up vote allowed
                if Product.objects.filter(
                    id=request.POST['vote_id']).filter(
                        product_type='I'):
                    ProductVote.objects.create(product=product[0], user_id=current_user.id)
                    return HttpResponse(request.POST['vote_id'])
                # else its a Feature and purchase required
                elif Sale.objects.filter(user_id=current_user.id).filter(saleproduct__product=request.POST['vote_id'])[0]:
                    ProductVote.objects.create(product=product[0], user_id=current_user.id)
                    return HttpResponse(request.POST['vote_id'])
            except IndexError:
                return HttpResponse(1)
        elif request.POST['action_type'] == 'time':
            try:
                product = Product.objects.filter(id=request.POST['time_id'])
                ProductTimeAssigned.objects.create(product=product[0], time_minutes=15)
                return HttpResponse(request.POST['time_id'])
            except IndexError:
                return HttpResponse(1)

    else:
        products = Product.objects.all()
        return render(request, "products.html", {"products": products})

@login_required
def new_product(request):
    current_user = request.user
    new_product_form = NewProductForm()
    if request.method == 'POST':
        form = NewProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user_id = current_user.id
            product.save()
            messages.add_message(
                request, messages.SUCCESS, 'Feature/Issue created')
            return redirect('products')
        else:
            messages.add_message(
                request, messages.ERROR, form.errors)

    args = {'new_product_form': new_product_form}
    return render(request, 'new_product.html', args)


@login_required
def edit_product(request, id=None, template_name='edit_product.html'):
    if id:
        product = get_object_or_404(Product, id=id)

    new_product_form = NewProductForm(
        request.POST or None,
        request.FILES or None,
        instance=product,
        id=id)

    if request.POST and new_product_form.has_changed():

        if new_product_form.is_valid():
            product.save()
            return redirect('products')

    elif request.POST:
        messages.add_message(
            request, messages.ERROR, 'No changes to save')

    args = {'new_product_form': new_product_form, 'id': id}
    return render(request, template_name, args)


@login_required
def delete_product(request, id=None, template_name='products.html'):
    current_user = request.user
    if id:
        product = get_object_or_404(Product, id=id)

        if SaleProduct.objects.filter(
                product_id=id):
            messages.add_message(
                request, messages.ERROR,
                "{} can not be deleted as users have paid funds".format(product))
        else:
            if Product.objects.filter(
                    id=id).filter(user_id=current_user.id):
                product.delete()
            else:
                messages.add_message(
                    request, messages.ERROR,
                    "{} can only be deleted by the creator".format(product))

    return redirect('products')


@login_required
def new_product_area(request):
    product_areas = ProductArea.objects.all()
    product_area_form = NewProductAreaForm()
    if request.method == 'POST':
        form = NewProductAreaForm(request.POST)
        if form.is_valid():
            # file is saved
            form.save()
            messages.add_message(
                request, messages.SUCCESS, 'Product Area created')
        else:
            messages.add_message(
                request, messages.ERROR, form.errors)

    args = {'new_product_area_form': product_area_form,
            'product_areas': product_areas}
    return render(request, 'new_product_area.html', args)


@login_required
def edit_product_area(request, id=None, template_name='edit_product_area.html'):
    product_areas = ProductArea.objects.all()
    if id:
        product_area = get_object_or_404(ProductArea, id=id)

    new_product_area_form = NewProductAreaForm(
        request.POST or None,
        instance=product_area)

    if request.POST and new_product_area_form.has_changed():

        if new_product_area_form.is_valid():
            product_area.save()
            return redirect('product_areas')

    elif request.POST:
        messages.add_message(
            request, messages.ERROR, 'No changes to save')

    args = {'new_product_area_form': new_product_area_form,
            'product_areas': product_areas}
    return render(request, template_name, args)

@login_required
def delete_product_area(request, id=None, template_name='edit_product_area.html'):
    if id:
        product_area = get_object_or_404(ProductArea, id=id)

        if Product.objects.filter(product_area_id=id):
            messages.add_message(
                request, messages.ERROR,
                "{} Cannot be deleted, Please delete Feature/Issue instead".format(product_area))
        else:
            product_area.delete()

    else:
        messages.add_message(
            request,
            messages.ERROR, "{} Not Deleted".format(product_area))

    return redirect('product_areas')


def all_product_areas(request):
    product_areas = ProductArea.objects.all()
    return render(
        request, 'product_areas.html', {'product_areas': product_areas})

products/templates/edit_product.html
{% extends 'base.html' %}
{% block page_title %}Create Features/Issue Requests Page{% endblock %}
{% block content %}
{% load widget_tweaks %}

<form enctype="multipart/form-data" method="post" novalidate>
  {% csrf_token %}

  {{ new_product_form.non_field_errors }}

  {% for hidden_field in new_product_form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  {{ form.errors }}

  <table>
    <tr>
      <th>
      </th>
      <td>
        <h2>Feature/Issue</h2>
      </td>
    </tr>
    {% for field in new_product_form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {% render_field field style="border: 2px dashed orange;" placeholder=field.name %}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
    <tr>
      <th>
      </th>
      <td>
        <button type="submit" onclick="issueZeroPrice();" class="button small button-form cart-column-text row-buttons one-cell-items product-save">Save</button>
        <a href="{% url 'products' %}"><button type="button" class="button small button-form cart-column-text row-buttons one-cell-items product-cancel">Cancel</button></a>
      </td>
    </tr>
  </table>
</form>

{% endblock %}

products/templates/edit_product_area.html
{% extends 'base.html' %}
{% block page_title %}Create Features/Issue Requests Page{% endblock %}
{% block content %}
{% load widget_tweaks %}

<form enctype="multipart/form-data" method="post" novalidate>
  {% csrf_token %}

  {{ new_product_area_form.non_field_errors }}

  {% for hidden_field in new_product_area_form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  {{ form.errors }}

  <table class="medium-width-table">
    <tr>
      <th>
      </th>
      <td>
        <h2>Feature/Issue Area</h2>
      </td>
    </tr>
    {% for field in new_product_area_form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {% render_field field style="border: 2px dashed orange;" placeholder=field.name %}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
    <tr>
      <th>
      </th>
      <td>
        <button type="submit" class="button small button-form cart-column-text row-buttons one-cell-items product-save">Save</button>
        <a href="{% url 'product_areas' %}"><button type="button" class="button small button-form cart-column-text row-buttons one-cell-items product-cancel">Cancel</button></a>
      </td>
    </tr>
  </table>
</form>

<table class="medium-width-table">
  <tr>
    <th>
      <h2>Existing Feature/Issue Areas</h2>
    </th>
    <td>
    </td>
  </tr>
  {% for product_area in product_areas %}
    <tr>
      <td class="description-heading">{{ product_area.name }}</td>
      <td>
      </td>
    </tr>
  {% endfor %}
</table>


{% endblock %}

products/templates/new_product.html
{% extends 'base.html' %}
{% block page_title %}Create Features/Issue Requests Page{% endblock %}
{% block content %}
{% load widget_tweaks %}

<form enctype="multipart/form-data" method="post" novalidate>
  {% csrf_token %}

  {{ new_product_form.non_field_errors }}

  {% for hidden_field in new_product_form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  {{ form.errors }}

  <table>
    <tr>
      <th>
      </th>
      <td>
        <h2>New Feature/Issue</h2>
      </td>
    </tr>
    {% for field in new_product_form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {% render_field field style="border: 2px dashed orange;" placeholder=field.name %}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
      <tr>
        <th></th>
        <td class="row-buttons">
          <button type="submit" onclick="issueZeroPrice();" class="button small product-new button-form">Save</button>
          <a href="{% url 'products' %}"><button type="button" class="button small button-form cart-column-text">Cancel</button></a>
        </td>
      </tr>
  </table>

</form>

{% endblock %}

products/templates/new_product_area.html
{% extends 'base.html' %}
{% block page_title %}Create Product Area Page{% endblock %}
{% block content %}
{% load widget_tweaks %}

<form method="post" novalidate>
  {% csrf_token %}

  {{ product_area_form.non_field_errors }}

  {% for hidden_field in new_product_area_form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  {{ form.errors }}

  <table class="medium-width-table">
    <tr>
      <th>
      </th>
      <td>
        <h2>New Feature/Issue Area</h2>
      </td>
    </tr>
    {% for field in new_product_area_form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {% render_field field style="border: 2px dashed orange;" placeholder=field.name %}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
    <tr>
      <th></th>
      <td class="row-buttons">
        <button type="submit" class="button small product-new button-form">Save</button>
        <a href="{% url 'products' %}"><button type="button" class="button small button-form cart-column-text">Cancel</button></a>
      </td>
    </tr>
  </table>
</form>

<table class="medium-width-table">
  <tr>
    <th>
      <h2>Existing Feature/Issue Areas</h2>
    </th>
    <td>
    </td>
  </tr>
  {% for product_area in product_areas %}
    <tr>
      <td class="description-heading">{{ product_area.name }}</td>
      <td>
      </td>
    </tr>
  {% endfor %}
</table>

{% endblock %}

products/templates/product_area.html
{% extends 'base.html' %}
{% block page_title %}Create Product Area Page{% endblock %}
{% block content %}
{% load widget_tweaks %}

<form method="post" novalidate>
  {% csrf_token %}

  {{ product_area_form.non_field_errors }}

  {% for hidden_field in product_area_form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  {{ form.errors }}

  <table border="1">
    {% for field in product_area_form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {% render_field field style="border: 2px dashed red;" placeholder=field.name %}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
  </table>

  <button type="submit" class="button small product-new">Save</button>
</form>

{% endblock %}

products/templates/product_areas.html
{% extends 'base.html' %}
{% block page_title %}Product Areas Page{% endblock %}
{% block content %}
  <table class="medium-width-table">
    <tr>
      <th>
      </th>
      <td>
        <h2>Feature/Issue Areas</h2>
      </td>
    </tr>
    {% for product_area in product_areas %}
      <tr>
        <td class="description-heading">{{ product_area.name }}</td>
        <td>
          <a href="{% url 'edit_product_area' product_area.id %}"><button type="button" id="edit_{{product_area.id}}" class="button small button-form cart-column-text row-buttons one-cell-items">Edit</button></a>
          <a href="{% url 'delete_product_area' product_area.id %}"><button type="button" id="delete_{{product_area.id}}" class="button small button-form cart-column-text row-buttons one-cell-items">Delete</button></a>
        </td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

products/templates/products.html
{% extends 'base.html' %}
{% block page_title %}Features/Issues Page{% endblock %}
{% block content %}

<ul class="accordion" data-accordion data-allow-all-closed="true">
{% for product in products %}

  <li class="accordion-item is-active" data-accordion-item>
      <!-- Accordion tab title -->
      {% ifequal product.product_type 'I' %}
        <a href="#" class="accordion-title issue white-color">
          <span class="line-heading">Name:</span> {{ product.name }}
          <span class="line-heading">Price:</span> {{ product.price }}
          <span class="line-heading">Total Cumulative Donations: </span> {{ product.total_amount_paid }}
          <span class="line-heading">Status:</span> {{ product.get_status_display }}
          {% if user.is_staff %}
            <span class="line-heading">Time:</span><span time-id="{{product.id}}"> {{ product.total_time }}</span>
          {% endif %}
        </a>
       {% else %}
       <a href="#" class="accordion-title feature white-color">
         <span class="line-heading">Name:</span> {{ product.name }}
         <span class="line-heading">Price:</span> {{ product.price }}
         <span class="line-heading">Total Cumulative Donations: </span> {{ product.total_amount_paid }}
         <span class="line-heading">Status:</span> {{ product.get_status_display }}
         {% if user.is_staff %}
           <span class="line-heading">Time:</span><span time-id="{{product.id}}"> {{ product.total_time }}</span>
         {% endif %}
       </a>
       {% endifequal %}

      <!-- Accordion tab content: it would start in the open state due to using the `is-active` state class. -->
      <div class="accordion-content" data-tab-content>
        <table class="stack product-table">
          <tbody>
            <tr>
              <td>
                <div data-id="{{product.id}}" class="image-detail" onclick="toggleFullSize(this)">
                  <img class="thumbnail-image-line-detail" src="{{ MEDIA_URL }}{{ product.image }}">
                </div>
                <div class="detail-paragraph">
                  <div class="description-element">
                    <h3 class="description-heading">Description {{ product.product_area }} {{ product.get_product_type_display }}</h3>
                  </div>
                  <div class="description-element">
                    <span class="description-text">{{ product.description }}</span>
                  </div>
                  <div>
                    <p class="file-name"><strong>Need:</strong> {{ product.get_product_need_display }}</p>
                    <p class="file-name"><strong>Complexity:</strong> {{ product.get_product_complexity_display }}</p>
                  </div>
                  <div>
                    <strong class="file-name">Document:</strong>
                    {% if product.product_document %}
                      <a href="{{ product.product_document.url }}" download="{{ product.file.name }}">
                        <span class="file-name">{{ product.filename }}</span>
                      </a>
                    {% endif %}
                  </div>
                </div>
              </td>
              <td class="add-to-cart-cell">
                <form method="post" action="{% url 'add_to_cart' product.id %}">
                  {% csrf_token %}
                  <div class="row grid-x cart-column">
                    <div class="small-1 large-1 columns add-to-cart-vote-form">
                      <p class="cart-column-text votes-label">Votes:
                          <span data-id="{{product.id}}">{{ product.total_votes }}</span></p>
                      <form method="post" action="{% url 'add_to_cart' product.id %}">
                        {% csrf_token %}
                        <div class="input-group">
                          <span class="input-group-label quantity-label cart-column-text">Quantity:</span>
                          <input name='quantity' id="quantity_{{product.id}}" type="number" min="1" max="999" class="form-control input-group-field small quantity-input cart-column-text" placeholder="" required>
                        </div>
                        {% if user.is_authenticated %}
                          {% if user.is_staff %}
                            <input type="button" onclick="plus15Mins(this)" class="button small button-cart-form cart-column-text" id="time_{{product.id}}" time-id="{{product.id}}" value="+15 Mins">
                            {% else %}
                            <input type="button" onclick="plusOneVote(this)" class="button small button-cart-form cart-column-text" id="vote_{{product.id}}" data-id="{{product.id}}" value="+1 Vote">
                          {% endif%}
                          {% if product.get_product_type_display == "Feature" %}
                            <input type="submit" id="add_to_cart_{{product.id}}" class="button small button-cart-form cart-column-text" value="Add to Cart">
                          {% else %}
                            <input type="submit" class="button small button-cart-form cart-column-text" value="Add to Cart" disabled=true>
                          {% endif %}
                          {% if product_count >= 1 %}
                            <a href="{% url 'view_cart' %}"><button type="button" class="button small button-cart-form cart-column-text">View Cart</button></a>
                          {% else %}
                            <a href="{% url 'view_cart' %}"><button type="button" class="button small button-cart-form cart-column-text" disabled=true>View Cart</button></a>
                          {% endif %}
                          <a href="{% url 'edit_product' product.id %}"><button type="button" id="edit_{{product.id}}" class="button small button-cart-form cart-column-text">Edit</button></a>
                          <a href="{% url 'delete_product' product.id %}"><button type="button" id="delete_{{product.id}}" class="button small button-cart-form cart-column-text">Delete</button></a>
                          <a href="{% url 'view_comments' product.id product.name %}"><button type="button" id="comments_{{product.id}}" class="button small button-cart-form cart-column-text">Comments</button></a>
                        {% else %}
                          <input type="button" title="Only 1 vote allowed per user" onclick="plusOneVote(this)" class="button small button-cart-form cart-column-text" id="vote_{{product.id}}" data-id="{{product.id}}" value="+1 Vote" disabled=true>
                          <input type="submit" class="button small button-cart-form cart-column-text" value="Add to Cart" disabled=true>
                          <a href="{% url 'edit_product' product.id %}"><button type="button" class="button small button-cart-form cart-column-text" disabled=true>Edit</button></a>
                          <a href="{% url 'delete_product' product.id %}"><button type="button" class="button small button-cart-form cart-column-text" disabled=true>Delete</button></a>
                          <a href="{% url 'view_comments' product.id product.name %}"><button type="button" class="button small button-cart-form cart-column-text" disabled=true>Comments</button></a>
                        {% endif %}
                      </form>
                    </div>
                  </div>
                </form>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

  </li>

{% endfor %}
</ul>

{% endblock %}

<!-- TODO: if reduced image shorter than description, documents the wrap below, clear left -->