cart/urls.py
from django.conf.urls import url
from .views import view_cart, add_to_cart, adjust_cart

urlpatterns = [
    url(r'^$', view_cart, name='view_cart'),
    url(r'^add/(?P<id>\d+)', add_to_cart, name='add_to_cart'),
    url(r'^adjust/(?P<id>\d+)', adjust_cart, name='adjust_cart'),
]

comments/urls.py
from django.conf.urls import url, include
from .views import view_comments, edit_comments

urlpatterns = [
    url(r'^edit/(?P<id>\d+)/(?P<name>[\w\d\s]+)/$',
        edit_comments, name="edit_comments"),
    url(r'^view/(?P<id>\d+)/(?P<name>[\w\d\s]+)/$',
        view_comments, name="view_comments"),
]

issue_tracker_0_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
# from django.urls import path
from django.views import static
from accounts import urls as accounts_urls
from products import urls as products_urls
from home import urls as home_urls
from cart import urls as carts_urls
from checkout import urls as checkout_urls
from comments import urls as comments_urls
from .settings import MEDIA_ROOT


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(home_urls)),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^products/', include(products_urls)),
    url(r'^cart/', include(carts_urls)),
    url(r'^checkout/', include(checkout_urls)),
    url(r'^comments/', include(comments_urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
]

comments/models.py
from django.db import models
from products.models import Product
from tinymce import HTMLField


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment_wiki = HTMLField('Content')

    def __str__(self):
        return self.comment_id

comments/forms.py
from django import forms
from tinymce.widgets import TinyMCE
from .models import Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class CommentForm(forms.ModelForm):
    comment_wiki = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Comment
        fields = ['comment_wiki']

    def __init__(self, *args, **kwargs):
        self.id = kwargs.pop('id', None)
        self.name = kwargs.pop('name', None)
        super(CommentForm, self).__init__(*args, **kwargs)

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import CommentForm
from .models import Comment


@login_required
def edit_comments(
        request, id=None, name=None, template_name='edit_comments.html'):
    """Wiki space for user comments and discussion."""
    try:
        comment = Comment.objects.get(product_id=id)
    except Comment.DoesNotExist:
        comment = None

    comment_form = CommentForm(instance=comment, id=id, name=name)

    if request.POST:
        comment = comment_form.save(commit=False)
        comment.product_id = id
        comment.comment_wiki = request.POST['comment_wiki']
        comment.save()
        messages.add_message(request, messages.SUCCESS, 'Comment Saved')
        return redirect('products')

    args = {'comment_form': comment_form, 'name': name}
    return render(request, template_name, args)


def view_comments(request, id=None, name=None, template_name='comments.html'):
    """Wiki space for user comments and discussion."""
    try:
        comment = Comment.objects.get(product_id=id)
    except Comment.DoesNotExist:
        comment = None

    if comment is None:
        return redirect('edit_comments', id=id, name=name)

    args = {'comment': comment, 'id': id, 'name': name}
    return render(request, template_name, args)

comments/templates/comments.html
{% extends 'base.html' %} {% block page_title %}Product comments placeholder{% endblock %} {% block page_heading %}Product comments placeholder{% endblock %}
{% load static %}
{% block content %}

<table class="medium-width-table">
  <tr>
    <th>
      <h2>{{ name }} Comments</h2>
    </th>
  </tr>
    <tr>
      <td>{{ comment.comment_wiki | safe }}</td>
    </tr>
    <tr>
      <td>
        <a href="{% url 'edit_comments' id name %}"><button type="button" class="button small button-form cart-column-text row-buttons one-cell-items">Edit</button></a>
        <a href="{% url 'products' %}"><button type="button" class="button small button-form cart-column-text row-buttons one-cell-items">Cancel</button></a>
      </td>
    </tr>
</table>
{% endblock %}

comments/templates/edit_comments.html
{% extends 'base.html' %} {% block page_title %}Product comments placeholder{% endblock %} {% block page_heading %}Product comments placeholder{% endblock %}
{% block content %}
{% load widget_tweaks %}
<script type="text/javascript">
tinymce.init({
  selector: '#id_comment_wiki'
});
</script>

  <table class="medium-width-table">
    <tr>
      <th>
        <h2>{{ name }} Comments</h2>
      </th>
    </tr>
      <tr>
        <td>
          {{ comment_form.media }}
          <form method="post" novalidate>
            {% csrf_token %}

            {{ comment_form.non_field_errors }}

            {% for hidden_field in comment_form.hidden_fields %}
              {{ hidden_field.errors }}
              {{ hidden_field }}
            {% endfor %}

            {{ form.errors }}

            {{ comment_form.comment_wiki | safe }}
        </td>
      </tr>
      <tr>
        <td class="add-to-cart-cell">
          <button type="submit" class="button small button-form cart-column-text row-buttons one-cell-items">Save</button>
          <a href="{% url 'products' %}"><button type="button" class="button small button-form cart-column-text row-buttons one-cell-items">Cancel</button></a>
        </td>
      </tr>
  </table>
  </form>

{% endblock %}